#!/bin/bash
# this script adds HANA replication between first and second DB node
# adds a standard internal load balancer and changes SAP config to utilize the new virtual IP address
# script should be called after right third script created DBs, loaded them and installed PAS/ASS instances

source parameters.txt
LOGFILE=/tmp/4_setup_HSR_add_LB.log
starttime=`date +%s`
RGNAME=RG-${AZLOCTLA}-${RESOURCEGROUP}
SIDLOWER=`echo $SAPSID|awk '{print tolower($0)}'`
HANALOWER=`echo $HANASID|awk '{print tolower($0)}'`
az account set --subscription $AZSUB >>$LOGFILE 2>&1

setup_hsr () {
    echo "###-------------------------------------###"
    echo "Enabling HANA System Replication"
    VMNAME=${SIDLOWER}db01
    echo 'sudo su - ${HANALOWER}adm' > /tmp/setup_hsr.sh
    echo ''


}
if [ $INSTALLDB2 == 'true' ]; then
    setup_hsr
fi


