---

# SLES Clustering
# Ref: https://documentation.suse.com/sle-ha/12-SP4/html/SLE-HA-install-quick/index.html
# https://rpm.pbone.net/index.php3/stat/45/idpl/27916721/numer/8/nazwa/ha-cluster-init
- name: Ensure Primary node initiates the Cluster
  when: inventory_hostname == hana_database.nodes[0].ip_admin_nic
  block:
    - name: Ensure csync2 is configured
      shell: crm cluster init -y csync2

    - name: Ensure corosync is configured
      shell: crm cluster init -y -u corosync

    - name: Ensure cluster (hdb_{{ hana_database.instance.sid | upper }}) is configured
      shell: "crm cluster init -y cluster --name 'hdb_{{ hana_database.instance.sid | upper }}'"

- name: Ensure Secondary node joins the Cluster
  when: inventory_hostname == hana_database.nodes[1].ip_admin_nic
  block:
    - name: Ensure the configuration files are synchronised
      shell: "crm cluster join -y -c {{ hana_database.nodes[0].ip_db_nic }} csync2"

    - name: Ensure the cluster is joined
      shell: "crm cluster join -y -c {{ hana_database.nodes[0].ip_db_nic }} cluster"

- name: Ensure HA Cluster password is set to something secure
  user:
    name: hacluster
    password: "{{ ha_cluster_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"

- name: Ensure cluster configuration contains correct details
  template:
    src: corosync.conf.j2
    dest: /etc/corosync/corosync.conf
    mode: 0600

- name: Ensure the Corosync service is restarted on primary node.
  when: inventory_hostname == hana_database.nodes[0].ip_admin_nic
  systemd:
    name: corosync
    state: restarted

- pause:
    seconds: 15

- name: Ensure the Corosync service is restarted on secondary node
  when: inventory_hostname == hana_database.nodes[1].ip_admin_nic
  systemd:
    name: corosync
    state: restarted

- pause:
    seconds: 15

- name: Ensure the cluster STONITH is created
  when: inventory_hostname == hana_database.nodes[0].ip_admin_nic
  block:

    - name: Check if SBD resource exists
      shell: crm resource list | grep 'sbd' | awk '{ print $1; }'
      register: sbd_device
      failed_when: false
    
    # "stonith-sbd" is the sbd device in most cases if there has already existed a SBD
    - name: Ensure current SBD device is stoped and removed if exists
      shell: |
        crm resource stop {{ sbd_device.stdout }}
        crm configure delete {{ sbd_device.stdout }}
      when: sbd_device.stdout | length > 0
      
    - name: Ensure SBD disk STONITH resource is created
      shell: >
        crm configure primitive stonith-sbd stonith:external/sbd \
        params pcmk_delay_max="15" \
        op monitor interval="15" timeout="15"
    
    - name: Check the current SBD status
      shell: crm_mon -1 | grep sbd
      register: sbd_report
      changed_when: False
      failed_when: False

    - debug:
        msg: "{{ sbd_report.stdout }}" 

    - name: Ensure maintenance mode is enabled
      shell: "crm configure property maintenance-mode=true"

    - name: Ensure CIB Bootstrap Options are set
      shell: >
        crm configure property \$id="cib-bootstrap-options"
        no-quorum-policy="ignore"
        stonith-enabled="true"
        stonith-action="reboot"
        stonith-timeout="900s"

    - name: Ensure the Resource Defaults are configured
      shell: >
        crm configure rsc_defaults \$id="rsc-options"
        resource-stickiness="1000"
        migration-threshold="5000"

    # Operation Default recommendation from section 5.3.1 in https://www.suse.com/media/white-paper/suse_linux_enterprise_server_for_sap_applications_12_sp1.pdf#page=26
    - name: Ensure the Operation Defaults are configured
      shell: >
        crm configure op_defaults \$id="op-options"
        timeout="600"

    - name: Ensure SAP HANA Topology resource is configured
      shell: >
        crm configure primitive rsc_SAPHanaTopology_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        ocf:suse:SAPHanaTopology
        operations \$id="rsc_sap2_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}-operations"
        op monitor interval="10" timeout="600"
        op start interval="0" timeout="600"
        op stop interval="0" timeout="300"
        params SID="{{ hana_database.instance.sid | upper }}" InstanceNumber="{{ hana_database.instance.instance_number }}"

    - name: Ensure SAP HANA Topology clone set resource is configured
      shell: >
        crm configure clone cln_SAPHanaTopology_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        rsc_SAPHanaTopology_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        meta clone-node-max="1" target-role="Started" interleave="true"

    - name: Ensure SAP HANA primitive resource is configured
      shell: >
        crm configure primitive rsc_SAPHana_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        ocf:suse:SAPHana
        operations \$id="rsc_sap_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}-operations"
        op start interval="0" timeout="{{ cluster_SAPHana_timeouts.start }}"
        op stop interval="0" timeout="{{ cluster_SAPHana_timeouts.stop }}"
        op promote interval="0" timeout="{{ cluster_SAPHana_timeouts.promote }}"
        op monitor interval="60" role="Master" timeout="{{ cluster_SAPHana_timeouts.monitor_master }}"
        op monitor interval="61" role="Slave" timeout="{{ cluster_SAPHana_timeouts.monitor_slave }}"
        params
        SID="{{ hana_database.instance.sid | upper }}"
        InstanceNumber="{{ hana_database.instance.instance_number }}"
        PREFER_SITE_TAKEOVER="true"
        DUPLICATE_PRIMARY_TIMEOUT="7200"
        AUTOMATED_REGISTER="false"

    - name: Ensure SAP HANA master-slave resource is configured
      shell: >
        crm configure ms msl_SAPHana_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        rsc_SAPHana_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        meta notify="true" clone-max="2" clone-node-max="1"
        target-role="Started" interleave="true"

    - name: Ensure SAP HANA Virtual IP resource is configured
      shell: >
        crm configure primitive rsc_ip_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }} ocf:heartbeat:IPaddr2
        meta target-role="Started"
        operations \$id="rsc_ip_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}-operations"
        op monitor interval="10s" timeout="20s"
        params ip="{{ hana_database.loadbalancer.frontend_ip }}"

    - name: Ensure SAP HANA Heartbeat netcat resource is configured
      shell: >
        crm configure primitive rsc_nc_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }} anything
        params binfile="/usr/bin/nc" cmdline_options="-l -k 62500"
        op monitor timeout=20s interval=10 depth=0

    - name: Ensure Group IP Address resource is configured
      shell: >
        crm configure group g_ip_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        rsc_ip_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        rsc_nc_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}

    - name: Ensure Co-Location constraint is configured
      shell: >
        crm configure colocation col_saphana_ip_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        4000:
        g_ip_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}:Started
        msl_SAPHana_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}:Master

    - name: Ensure Resource order is configured
      shell: >
        crm configure order ord_SAPHana_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        Optional:
        cln_SAPHanaTopology_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}
        msl_SAPHana_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}

    - name: Ensure any required cluster resources are cleaned up
      shell: "crm resource cleanup rsc_SAPHana_{{ hana_database.instance.sid | upper }}_HDB{{ hana_database.instance.instance_number }}"

    - name: Ensure maintenance mode is disabled
      shell: "crm configure property maintenance-mode=false"
