trigger: none
pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - deploy/terraform/bootstrap/sap_library/*
    - deploy/terraform/run/sap_library/*
    - deploy/terraform/terraform-units/modules/sap_library/*
variables:
  - group: azure-config-variables
  - group: azure-sap-hana-pipeline-secrets
  - template: templates/variables.yaml
stages:
- stage:
  pool:
    vmImage: "ubuntu-18.04"
  variables:
    ssh_timeout_s: 120
  jobs:
  - job: createSAPLib
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/saplib/create-saplib-steps.yml
        parameters:
          branch_name: $(targetBranchName)
          saplib_env: "$(Build.BuildId)"
      - template: templates/saplib/validate-saplib-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          saplib_env: "$(Build.BuildId)"
      - template: templates/saplib/create-saplib-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          saplib_env: "$(Build.BuildId)"
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
  - job: deleteSAPLib
    dependsOn: createSAPLib
    condition: or(succeededOrFailed(), always())
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/saplib/delete-saplib-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          saplib_env: "$(Build.BuildId)"
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
