# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                            Package Installation                             |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
#
# Task: 2.1       - Package Installation for SAP

- name:             2.1 - Import package list
  include_vars:     sap-packages.yaml

- name:             "2.1 - Install OS packages for SAP: {{ ansible_os_family|upper }}-{{ ansible_distribution_major_version }}"
  package:
    name:           "{{ item }}" 
    state:          present
  loop:             "{{ packages[ansible_os_family|lower] }}"

# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
