packages:
    redhat7:
      - "@base"
      - gtk2
      - libicu
      - xulrunner
      - sudo
      - tcsh
      - libssh2
      - expect
      - cairo
      - graphviz
      - iptraf-ng
      - krb5-workstation
      - krb5-libs
      - libpng12
      - nfs-utils
      - lm_sensors
      - rsyslog
      - openssl
      - PackageKit-gtk3-module
      - libcanberra-gtk2
      - libtool-ltdl
      - xorg-x11-xauth 
      - numactl
      - xfsprogs
      - net-tools
      - bind-utils
      - chrony
      - gdisk
      - sg3_utils
      - lvm2
      - numad
      - cifs-utils

    redhat8:
      - "@base"
      - gtk2
      - libicu
      - sudo
      - tcsh
      - libssh2
      - expect
      - cairo
      - graphviz
      - iptraf-ng
      - krb5-workstation
      - krb5-libs
      - libpng12
      - nfs-utils
      - lm_sensors
      - rsyslog
      - openssl
      - PackageKit-gtk3-module
      - libcanberra-gtk2
      - libtool-ltdl
      - xorg-x11-xauth 
      - numactl
      - xfsprogs
      - net-tools
      - bind-utils
      - chrony
      - gdisk
      - sg3_utils
      - lvm2
      - numad
      - cifs-utils      

    suse12: 
      - libyui-qt-pkg7
      - glibc
      - systemd
      - tuned
      - numad

    suse15: 
      - libyui-qt-pkg11
      - glibc
      - systemd
      - tuned
      - numad     
